package greendao;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

import com.ideacoolweather.android.model.County;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "COUNTY".
*/
public class CountyDao extends AbstractDao<County, Void> {

    public static final String TABLENAME = "COUNTY";

    /**
     * Properties of entity County.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property CountyId = new Property(0, int.class, "CountyId", false, "COUNTY_ID");
        public final static Property CountyName = new Property(1, String.class, "countyName", false, "COUNTY_NAME");
        public final static Property WeatherId = new Property(2, String.class, "weatherId", false, "WEATHER_ID");
        public final static Property CityId = new Property(3, int.class, "cityId", false, "CITY_ID");
    };


    public CountyDao(DaoConfig config) {
        super(config);
    }
    
    public CountyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"COUNTY\" (" + //
                "\"COUNTY_ID\" INTEGER NOT NULL ," + // 0: CountyId
                "\"COUNTY_NAME\" TEXT," + // 1: countyName
                "\"WEATHER_ID\" TEXT," + // 2: weatherId
                "\"CITY_ID\" INTEGER NOT NULL );"); // 3: cityId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"COUNTY\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, County entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCountyId());
 
        String countyName = entity.getCountyName();
        if (countyName != null) {
            stmt.bindString(2, countyName);
        }
 
        String weatherId = entity.getWeatherId();
        if (weatherId != null) {
            stmt.bindString(3, weatherId);
        }
        stmt.bindLong(4, entity.getCityId());
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, County entity) {
        stmt.clearBindings();
        stmt.bindLong(1, entity.getCountyId());
 
        String countyName = entity.getCountyName();
        if (countyName != null) {
            stmt.bindString(2, countyName);
        }
 
        String weatherId = entity.getWeatherId();
        if (weatherId != null) {
            stmt.bindString(3, weatherId);
        }
        stmt.bindLong(4, entity.getCityId());
    }

    @Override
    public Void readKey(Cursor cursor, int offset) {
        return null;
    }    

    @Override
    public County readEntity(Cursor cursor, int offset) {
        County entity = new County( //
            cursor.getInt(offset + 0), // CountyId
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1), // countyName
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2), // weatherId
            cursor.getInt(offset + 3) // cityId
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, County entity, int offset) {
        entity.setCountyId(cursor.getInt(offset + 0));
        entity.setCountyName(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
        entity.setWeatherId(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
        entity.setCityId(cursor.getInt(offset + 3));
     }
    
    @Override
    protected final Void updateKeyAfterInsert(County entity, long rowId) {
        // Unsupported or missing PK type
        return null;
    }
    
    @Override
    public Void getKey(County entity) {
        return null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
